server:
  port: 8080

spring:
  application:
    name: e-commerce-app

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jooq:
    sql-dialect: mysql

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: create-drop
